---
name: Docker Build Action

on:
#   push:
#     branches:
#     - main
  workflow_dispatch:
    inputs:
      gardener_branch:
        description: 'Gardener branch to build'
        required: true
        type: string
      mcm_branch:
        description: 'MCM branch to build'
        required: false
        type: string
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    gardener:
        name: Gardener Build
        runs-on: ubuntu-latest
        if: ${{ inputs.gardener_branch }}

        steps:
          - name: Log in to the container registry
            uses: docker/login-action@v4
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ secrets.DOCKER_REGISTRY_USER }}
              password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

          - name: Checkout
            uses: actions/checkout@v6

          - name: set gardener version
            run: echo "BUILD_BRANCH=${{ inputs.gardener_branch }}" >> $GITHUB_ENV

          - name: build gardener images
            run: gardener/build.sh

    mcm:
        name: Machine Controller Manager Build
        runs-on: ubuntu-latest
        if: ${{ inputs.mcm_branch }}

        steps:
          - name: Log in to the container registry
            uses: docker/login-action@v4
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ secrets.DOCKER_REGISTRY_USER }}
              password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

          - name: Checkout
            uses: actions/checkout@v6

          - name: set gardener version
            run: echo "BUILD_BRANCH=${{ inputs.mcm_branch }}" >> $GITHUB_ENV

          - name: build gardener images
            run: machine-controller-manager/build.sh